version: "3.8"

services:
  db:
    image: postgres:9.4
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 3000:8080

volumes:
  dbdata:
